artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/bmsg7/binsenseai/raw/main/binsimages.zip
  local_data_file: artifacts/data_ingestion/binsimages.zip
  unzip_dir: artifacts/data_ingestion

data_reading_and_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/binsimages.csv,
  bins_data: artifacts/data_ingestion